### ISSUE TITLE
ssh extent

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#106]
Note for selves, just got burnt by this:
```
> extent(readssh(as.Date("2020-01-01")))
class      : Extent
xmin       : 0
xmax       : 360
ymin       : -90
ymax       : 90

> extent(readssh(as.Date("2020-09-01")))
class      : Extent
xmin       : -180
xmax       : 180
ymin       : -90
ymax       : 90
```

ssh data files changed from 0->360 to -180->180 in mid 2020??

**Comment by mdsumner** [comment]
Ouch!!!!

**Comment by mdsumner** [comment]
looks like an april fool's joke really stuck

I have no idea what to do ...


![image](https://user-images.githubusercontent.com/4107631/106087864-fb004200-6178-11eb-864f-1bb7c8e32a4d.png)

**Comment by mdsumner** [comment]
@raymondben in their PDF

http://marine.copernicus.eu/documents/PUM/CMEMS-SL-PUM-008-032-062.pdf

the example from "nrt_global_allsat_phy_l4_20191124_20191130" has a -180,180 extent in the ncdump output, I checked the current files from 1993 they were created  2019-01-17 - so maybe there's a reprocessing sweep pending ...

**Comment by raymondben** [comment]
I assume that they don't *re*process near-real-time files after the 6-day window though - any reprocessing would be happening in the SEALEVEL_GLO_PHY_L4_REP_OBSERVATIONS_008_047 data. Do those suffer the same grid wackiness?

**Comment by mdsumner** [comment]
yes those are what I checked, `ftp://my.cmems-du.eu/Core/SEALEVEL_GLO_PHY_L4_REP_OBSERVATIONS_008_047/dataset-duacs-rep-global-merged-allsat-phy-l4/1993/01/dt_global_allsat_phy_l4_19930101_20190101.nc` currently is 0,360 - the change is within the NRT timeline (oh but perhaps they get re-aligned once moved out of NRT ...?)

**Comment by mdsumner** [comment]
Fixed in part

- [x] readcurr
- [ ] readssh
- [ ] read_sla_daily, read_ugosa_daily, read_vgosa_daily, read_ugos_daily, read_vgos_daily, read_err_daily

**Comment by mdsumner** [comment]
code to identify NRT and longitude orientation for all files, and data frame of the files attached

```R
library(dplyr)
files <- raadfiles::get_raad_filenames() %>% 
  transmute(fullname = file.path(root, file)) %>% 
  filter(stringr::str_detect(fullname, "cmems-du.eu/Core.*global_allsat_phy_l4_.*nc$")) %>% 
  mutate(nrt = stringr::str_detect(fullname, "nrt"), 
         date = as.POSIXct(as.Date(stringr::str_extract(basename(.data$fullname), "[0-9]{8}"),
                                   "%Y%m%d"),tz = "UTC"))




library(furrr)
plan(multicore)

files$atlantic <- future_map_lgl(files$fullname, raadtools:::is_atlantic)
saveRDS(files, "is_nrt_atlantic.rds")


library(ggplot2)

ggplot(d, aes(date, nrt)) + geom_jitter(aes(colour = atlantic), pch = 19, cex = .3) + geom_vline(data = data.frame(date = as.POSIXct("2020-04-01")), aes(xintercept = date))


```


![image](https://user-images.githubusercontent.com/4107631/114339779-5ac39200-9b99-11eb-800b-8f598faf0c82.png)

[is_nrt_atlantic.zip](https://github.com/AustralianAntarcticDivision/raadtools/files/6293829/is_nrt_atlantic.zip)

**Comment by mdsumner** [comment]
a bit more smoking-gun-ish when you look at processing date

![image](https://user-images.githubusercontent.com/4107631/114484350-66709080-9c4d-11eb-9fb7-8c5938cbb2c5.png)


![image](https://user-images.githubusercontent.com/4107631/114484388-76887000-9c4d-11eb-9ebe-53665271ab5f.png)
