### ISSUE TITLE
 unable to find an inherited method for function ‘extract’ for signature ‘"function", "tbl_df"

### ISSUE THREAD

**Issue by fooxhd** [AustralianAntarcticDivision/raadtools#116]
Hi Mike,

I'm suddenly getting an error when I run the following code:

`d$sst <- extract(readsst, d[, c("lon", "lat", "date")])`

corresponding error:
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘extract’ for signature ‘"function", "tbl_df"’
```
I tried converting the `tbl_df` to a regular `data.frame` - still didn't work.

However `extract` works when I do it for topo:
`d$topo <- extract(readtopo("etopo1"), d[, c("lon", "lat")]) 
`

Not sure why adding a `date` column would lead to that error.

Hope you can help, thanks!

**Comment by mdsumner** [comment]
I think you need `raster::extract(readsst, d[, c("lon", "lat", "date")])` or possibly `raadtools::extract(readsst, d[, c("lon", "lat", "date")])`

HTH!

**Comment by fooxhd** [comment]
Thanks Mike! It didn't work. But I found a way to get around it by looping through dates. All good now :)
