### ISSUE TITLE
Ocean current data units

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/raadtools#117]
The helpfile for `readcurr()` states that the velocity is returned in cm/s, but I believe the unit is actually m/s per the Copernicus site (and magnitude only should then also be in m, not cm?).

See, for example:
[https://view-cmems.mercator-ocean.fr/SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046](https://view-cmems.mercator-ocean.fr/SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046)

**Comment by mdsumner** [comment]
thanks Ryan, should be fixed now
