### ISSUE TITLE
no files found in the 'raadfiles.filename.database'

### ISSUE THREAD

**Issue by fooxhd** [AustralianAntarcticDivision/raadtools#118]
Hi Mike,

Not sure if it's my computer but I'm suddenly getting this error when I try to extract any environmental data:
![image](https://user-images.githubusercontent.com/18390092/146277526-cb52ce6e-4e43-48f0-b5d5-e4869d5b768f.png)

Was wondering if anyone else is also having the same issue?

**Comment by raymondben** [comment]
If you're on one of the NecTAR VM's, they had a forced shutdown for maintenance the other day and many seem not to have re-mounted their disks properly on restart. Am checking them all this morning.

**Comment by fooxhd** [comment]
Thanks Ben, it seems to be working now :)
