### ISSUE TITLE
read_par error

### ISSUE THREAD

**Issue by KimBaldry** [AustralianAntarcticDivision/raadtools#135]
Error: 'reproj_xy' is not an exported object from 'namespace:reproj' 

> traceback()
4: .local(x, y, ...)
3: raadtools::extract(read_par, coords[is.finite(coords$Lon), ])
2: raadtools::extract(read_par, coords[is.finite(coords$Lon), ]) at light.R#4
1: add_light(results[which(results$YYYY > 2002), ])

Not sure where this is coming from...

**Comment by mdsumner** [comment]
I failed to put reproj required version in the deps 🙏

remotes::install_github("hypertidy/reproj")

to workaround but I'll fix here, and sort out the VMs, thanks!

**Comment by KimBaldry** [comment]
Thanks Mike :)
