### ISSUE TITLE
Can't read current files

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/raadtools#141]
Trying to read in current produces an error.

`readcurr("2002-01-15")`

returns

`Error in R_nc4_open: No such file or directory
Error in ncdf4::nc_open(filename, readunlim = FALSE, suppress_dimvals = TRUE) : 
  Error in nc_open trying to open file /rdsi/PUBLIC/raad/data/my.cmems-du.eu/Core/SEALEVEL_GLO_PHY_L4_REP_OBSERVATIONS_008_047/dataset-duacs-rep-global-merged-allsat-phy-l4/2002/01/dt_global_allsat_phy_l4_20020115_20190101.nc`

**Comment by mdsumner** [comment]
this might be a server restart issue, just something I've been meaning to ask Ben about so we can chat on this tomorrow 🙏

**Comment by raymondben** [comment]
Copernicus have shut down their old access mechanisms and everything is now through their object storage, so our directory structure has changed. That file is now located at `/rdsi/PUBLIC/raad/data/data.marine.copernicus.eu/SEALEVEL_GLO_PHY_L4_MY_008_047/cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.25deg_P1D_202112/2002/01/dt_global_allsat_phy_l4_20020115_20210726.nc`.

The base file name has not meaningfully changed, so the existing raadfiles code should not require any changes (?). But the file list is obviously out of date. Maybe it needs a forced refresh?

**Comment by mdsumner** [comment]
the file list is running still, give it a day or so and I'll check

**Comment by raymondben** [comment]
Fixed now with file index update completed.

```
> readcurr("2002-01-15")
class      : RasterStack
dimensions : 720, 1440, 1036800, 2  (nrow, ncol, ncell, nlayers)
resolution : 0.25, 0.25  (x, y)
extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +a=6371000 +b=6371000 +no_defs
names      : Absolute.geostrophic.velocity..zonal.component, Absolute.geostrophic.velocity..meridian.component
time        : 2002-01-15, 2002-01-15
```
