### ISSUE TITLE
Can't find bathymetry file

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/raadtools#143]
`readtopo(topo = "gebco_19")`

returns error

`Error in .find_files_generic(pattern) : no files found`

**Comment by mdsumner** [comment]
probably need either to restart the session or do 'sudo mount -a' in the system then new session, but some of this is Ben stuff atm while the machine is getting updated

also note there should be gebco_21 now, and we can hit up 23 via other means

**Comment by raymondben** [comment]
It's not mount or session - it's something to do with that particular file, because:
```
> raadfiles::gebco14_files()
# A tibble: 1 × 2
  fullname                                                     root
  <chr>                                                        <chr>
1 /rdsi/PUBLIC/raad/data/www.bodc.ac.uk/gebco/GEBCO_2014_2D.nc /rdsi/PUBLIC/raa…

```
(I get the same error with gebco19)

**Comment by mdsumner** [comment]
ok!

**Comment by raymondben** [comment]
Fixed in https://github.com/AustralianAntarcticDivision/raadfiles/commit/4e8f406feb5d523a435e3ceddcad83e0dba617d9
```
> readtopo(topo = "gebco_19")
class      : RasterLayer
dimensions : 43200, 86400, 3732480000  (nrow, ncol, ncell)
resolution : 0.004166667, 0.004166667  (x, y)
extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +datum=WGS84 +no_defs
source     : GEBCO_2019.tif
names      : GEBCO_2019

```
