### ISSUE TITLE
no files found in the 'raadfiles.filename.database'

### ISSUE THREAD

**Issue by rkonijnenberg16** [AustralianAntarcticDivision/raadtools#147]
Hi Team,
I am using a VM and keep getting this error when trying to load oisst files:

"no files found in the 'raadfiles.filename.database'
and no root directories found.
Error in .find_files_generic(pattern) : no files found"

Thanks,
Becky

**Comment by raymondben** [comment]
Hi @rkonijnenberg16 - which VM are you on? I checked a few and am not seeing this issue.

**Comment by rkonijnenberg16** [comment]
Hi Ben,

using one of the NECTAR R Studio instances for one of the UTAS modeling groups. I'll send you the full address in an email. It worked fine 4 weeks ago, which is why I am a bit stumped...

Cheers,
Becky
