### ISSUE TITLE
dud ocean colour netcdf files?

### ISSUE THREAD

**Issue by SnowpeaSoho** [AustralianAntarcticDivision/raadtools#148]
I have been on raadtools() updating myself on how the readchl function is working these days … I think I’ve worked out the workflow (ie if you want daily info - not mean fields compiled over any supplied date period - just submit one date and spatial extent to pull the daily L3 binned SO chl raster and then run the extract directly over that)

I’ve setup a loop over dates (commencing winter 2019) and all goes well until we hit the files for 2021; for this and those after I get netcdf read errors, even though in the mounted rdsi cache the netcdfs seem to be present and don’t appear to be any different. Same result using different netcdf packages in R. Any insight into this? Apparently every file after this is a dud, they all failed to download properly and no-one noticed ... :O

>   print(paste(dates[i] ,": Date" ,i ,"of", length(dates)))
[1] "2021-01-24 : Date 161 of 419"
>   chl <- readchla(dates[i], product = "MODISA", xylim=ee) # raster becomes 2.5MB instead of >11
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(filename, readunlim = FALSE, suppress_dimvals = TRUE) : 
  Error in nc_open trying to open file /rdsi/PUBLIC/raad/data/oceandata.sci.gsfc.nasa.gov/MODISA/Mapped/Daily/4km/chlor/2021/AQUA_MODIS.20210124.L3m.DAY.CHL.chlor_a.4km.nc (return_on_error= FALSE )

> readchla()
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(filename, readunlim = FALSE, suppress_dimvals = TRUE) : 
  Error in nc_open trying to open file /rdsi/PUBLIC/raad/data/oceandata.sci.gsfc.nasa.gov/MODISA/Mapped/Daily/4km/chlor/2024/AQUA_MODIS.20240331.L3m.DAY.CHL.chlor_a.4km.nc (return_on_error= FALSE )

> fp
[1] "/rdsi/PUBLIC/raad/data/oceandata.sci.gsfc.nasa.gov/MODISA/Mapped/Daily/4km/chlor/2021/AQUA_MODIS.20210123.L3m.DAY.CHL.chlor_a.4km.nc"
> nc_open(fp)
Error in R_nc4_open: NetCDF: Unknown file format
Error in nc_open(fp) : 
  Error in nc_open trying to open file /rdsi/PUBLIC/raad/data/oceandata.sci.gsfc.nasa.gov/MODISA/Mapped/Daily/4km/chlor/2021/AQUA_MODIS.20210123.L3m.DAY.CHL.chlor_a.4km.nc (return_on_error= FALSE )

**Comment by raymondben** [comment]
Yeah, unfortunately all oceancolour downloads were broken after a curl update earlier this year. I fixed it for other sources but missed oceancolour. Fixing it now, and then it'll have to re-run to download all those broken files ...

**Comment by SnowpeaSoho** [comment]
thanks for prompt answer! sounds good, please let me know once the download is complete :)

**Comment by raymondben** [comment]
Should be good to go now. You might have to reload your R session to force raadtools to refresh its file list
