### ISSUE TITLE
put ibcso background tif in collection

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadtools#15]
Can we put this in webdav, or as a side effect by raadsync? file.path(datadir,  "bathymetry", "ibcso", "image", "ibcso_background_hq.tif")

Pretty sure that we can gdal_translate the pdf and get a GeoTIFF from it.

**Comment by raymondben** [comment]
Done: it's now part of the default IBCSO data source. Because it comes from a different server (www.ibcso.org not Pangaea) it resides in data/www.ibcso.org/data/
