### ISSUE TITLE
Change AMSR-E sea ice data location

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#52]
The AMSR-E Artist sea ice data has moved from ftp-projects.zmaw.de to ftp-projects.cen.uni-hamburg.de. So the directory in which the data files are stored has changed. I have renamed the existing directory to the new name but put a symbolic link in place so the old one will work until raadtools is updated (at least it will work on RDSI, doubt it will work on the windows fileshare copy)

**Comment by mdsumner** [comment]
Looks good, 467c1069fd0699f512f02cf1e75bb7511f645d0b

confirmed with 

```R
readice(product = "amsr", latest = FALSE)
readice(product = "amsr", latest = TRUE)

icf <- icefiles(product = "amsr")
icf$file[c(1, nrow(icf))]
[1] "data/ftp-projects.cen.uni-hamburg.de/seaice/AMSR-E_ASI_IceConc/no_landmask/hdf/s6250/2002/06_Jun/asi-nl-s6250-20020619-v5i.hdf"
[2] "data/www.iup.uni-bremen.de+8084/amsr2data/asi_daygrid_swath/s6250/2017/jun/Antarctic/asi-AMSR2-s6250-20170625-v5.hdf"    
```

(I had started using a db for the files, but that wasn't picking up the new files - since 5 June 2017 - so I've reverted to the original file scan, to be reviewed again soon with raadfiles).

**Comment by mdsumner** [comment]
This is now covered by the new approach, with specifically named functions (the old "product=option" path should fail now. 

```R
read_amsr_ice(latest = FALSE)
read_amsr_ice(latest = TRUE)

icf <- raadfiles::amsr_daily_files()
icf$fullname[c(1, nrow(icf))]
#[1] "ftp-projects.cen.uni-hamburg.de/seaice/AMSR-E_ASI_IceConc/no_landmask/hdf/s6250/2002/06_Jun/asi-nl-s6250-20020619-v5i.hdf"
#[2] "www.iup.uni-bremen.de+8084/amsr2data/asi_daygrid_swath/s6250/2017/aug/Antarctic/asi-AMSR2-s6250-20170820-v5.hdf"
```
