### ISSUE TITLE
GEBCO file not found in readbathy

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/raadtools#65]
Running:
```
library(raadtools)
dep <- readbathy(topo = "gebco_08", xylim = c(-180, 180, -90, -20))
```

Gives the errror:
Error in R_nc4_open: No such file or directory
Error in ncdf4::nc_open(filename) : 
  Error in nc_open trying to open file /rdsi/PRIVATE/raad/data/www.bodc.ac.uk/gebco/GRIDONE_2D.nc
In addition: Warning message:
In topofile(topo = topo, polar = polar, lon180 = lon180, ...) :
  cannot file /rdsi/PRIVATE/raad/data/www.bodc.ac.uk/gebco/GRIDONE_2D.nc

**Comment by raymondben** [comment]
Ryan - on which machine - the RAATD VM?On 7 Nov. 2017 7:28 pm, Ryan Reisinger <notifications@github.com> wrote:Running:
library(raadtools)
dep <- readbathy(topo = "gebco_08", xylim = c(-180, 180, -90, -20))

Gives the errror:
Error in R_nc4_open: No such file or directory
Error in ncdf4::nc_open(filename) :
Error in nc_open trying to open file /rdsi/PRIVATE/raad/data/www.bodc.ac.uk/gebco/GRIDONE_2D.nc
In addition: Warning message:
In topofile(topo = topo, polar = polar, lon180 = lon180, ...) :
cannot file /rdsi/PRIVATE/raad/data/www.bodc.ac.uk/gebco/GRIDONE_2D.nc

**Comment by ryanreisinger** [comment]
Yes, on RAATD VM - http://144.6.225.208:8787/

**Comment by raymondben** [comment]
Ah, the path should be `/rdsi/PRIVATE/raad/data_local/...`. One for @mdsumner.

**Comment by mdsumner** [comment]
grrr welcome to my day, something went wrong and I've whacked a few moles but still not figured out what's happening :|

**Comment by mdsumner** [comment]
this problem went away, making room for new ones
