### ISSUE TITLE
directory changes

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadtools#67]
notes from the bb-frontline: 

1. cryosat2 was previously in something.leeds.ac.uk, now in earth.esa.int (and simplified format, just one nc file). 
2. the IBCSO background raster (not the data, just the image) is moving from www.ibcso.org to  hs.pangaea.de (alongside the actual IBCSO data). 
3. OIv2 SST daily moving from eclipse.ncdc.noaa.gov, to www.ncei.noaa.gov AND WITH DIFFERENT DIRECTORY STRUCTURE. The eclipse.ncdc directory does not contain any data after end 2017.

**Comment by raymondben** [comment]
Does raadtools recognize the data_deprecated directory? If I move the www.ibcso.org and ecipse.ncdc.noaa.gov directories from data/ to data_deprecated/, will that break raadtools?

**Comment by mdsumner** [comment]
Actually I think the file scan is robust to that, it will find the old files if not the new so that buys time. Not every client sees PRIVATE but most do still

**Comment by mdsumner** [comment]
Re Cryosat2 I also see this, which seems not ideal :) - I think my filter logic would not actively prevent finding this, though a unique-filter would get it right, incidentally

 earth.esa.int/documents/10174/3082676/__MACOSX/._Antarctica_DEM_CryoSat2_v1.2.nc

The logic to avoid that better in blueant than raad*, but probably worth an email to them?

**Comment by mdsumner** [comment]
Updates to raadfiles to support these changes  https://github.com/AustralianAntarcticDivision/raadfiles/commit/fce3b170717d4a2e312f3d5bf6fb8bad003c71d6


And in raadtools:   https://github.com/AustralianAntarcticDivision/raadtools/commits/master
