### ISSUE TITLE
ibcso bedrock option

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#69]
add option to use the bedrock ibcso (currently using ice surface)

**Comment by mdsumner** [comment]
Try it!

```R
ics <- readtopo("ibcso_is")

bed <- readtopo("ibcso_bed")
ex <- extent(ics, 4000, 5500, 4500, 5500)
plot(crop(ics, ex))
plot(crop(bed, ex))

```

The bed format is a lot slower for some reason, use readAll(bed) to unlink from file, after crop if needed. 

(crop will cut from file for a .tif automatically, but not for GMT .grd - it's possible to make raster/ncdf4 deal with this quicker but not today :)

**Comment by mdsumner** [comment]
Re the speed thing, it's about this which I think raster can't pass down: 

```R
system.time(nc <- nc_open(topofile("ibcso_bed")))
   user  system elapsed 
  1.624   2.188   4.155 
> system.time(nc <- nc_open(topofile("ibcso_bed"), suppress_dimvals = TRUE))
   user  system elapsed 
  0.632   0.004   0.642 
```

**Comment by mdsumner** [comment]
I didn't expect these to be so different ??

``` r
library(raadtools)
#> Loading required package: raster
#> Loading required package: sp
#> global option 'raadfiles.data.roots' set:
#> '/rdsi/PRIVATE/raad/data
#>  /rdsi/PRIVATE/raad/data_local
#>  /rdsi/PRIVATE/raad/data_staging
#>  /rdsi/PRIVATE/raad/data_deprecated
#>  /rdsi/PUBLIC/raad/data'
#> Uploading raad file cache as at 2019-06-13 05:19:04 (968720 files listed)
ics <- readtopo("ibcso_is")

bed <- readtopo("ibcso_bed")
ex <- extent(ics, 4000, 5500, 4500, 5500)
grey <- grey(seq(0, 1, length = 26))
plot(crop(ics, ex), col = grey, zlim = c(-1650, 1660))
```

![](https://i.imgur.com/SoyeDrc.png)

``` r
plot(crop(bed, ex), col = grey, zlim = c(-1650, 1660))
```

![](https://i.imgur.com/GL5AHdG.png)

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
this is done, we can revisit if 'readtopo("ibcso_bed")' is not good enough
