### ISSUE TITLE
ramp dem

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#70]
sidads.colorado.edu/pub/DATASETS/nsidc0082_radarsat_dem_v02/200M/BINARY/

it has two versions, relative to two different geoids.
see http://nsidc.org/data/nsidc-0082

**Comment by mdsumner** [comment]
blueant trail https://github.com/AustralianAntarcticDivision/blueant#radarsat-antarctic-digital-elevation-model-v2

**Comment by mdsumner** [comment]
Try it!

```R
ics <- readtopo("ibcso_is")

bed <- readtopo("ibcso_bed")
ex <- extent(ics, 4000, 5500, 4500, 5500)
plot(crop(ics, ex))
plot(crop(bed, ex))

```

The bed format is a lot slower for some reason, use readAll(bed) to unlink from file, after crop if needed. 

(crop will cut from file for a .tif automatically, but not for GMT .grd - it's possible to make raster/ncdf4 deal with this quicker but not today :)

**Comment by mdsumner** [comment]
Oh ffs I linked the wrong issue ...

**Comment by mdsumner** [comment]
The tar.gz is still .tar - is this bb's first tarball?

**Comment by raymondben** [comment]
Arg, yes it is. Hrumph.

**Comment by mdsumner** [comment]
happy to proceed with a function if you just manually untar, save the bb stuff for later?

**Comment by raymondben** [comment]
Manual untar done. bb should be able to use `utils::untar` without too much drama. I hope.
