### ISSUE TITLE
raadclient - general instructions

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadtools#73]
NOTE: nectar interface has changed a little, some of this is slightly out of date - see Network/Security Groups instead of "Access and Security", and Compute/Images instead of "Images". 2018-08-09

These instructions refer to the Nectar compute research cloud in Australia, and for launching an Ubuntu-flavoured image for running R and RStudio Server, with access to our "raadtools" file collection. 

The R and RStudio installed are 3.5.1 and 1.1.456, current at 2018-10-16 The installation includes many geo-spatial packages, as well as our facilities raadtools/raadfiles for reading our data collection. 

* Go to nectar dash board https://dashboard.rc.nectar.org.au
* Ensure you have these security groups in (under Network/Security Groups): 
  * RStudio Server Security Group with rule for port 8787
  * SSH Security group with rule for port 22
* Go to Compute/Images and look for "raadclient*" - currently it is called "raadclient05_20180514"
* Begin process to launch that with your key, make sure image is *larger* than "m2.tiny" (i.e. "m2.medium" is probably the smallest possible)
* Now click on the RStudioServer and SSH in the security groups - it does't matter what Availability Zone is used (though see below)
* Then go to [ip-address]:8787 log in with rstudio/rstudio
* Test the raadtools facility with `library(raadtools); readice(latest = TRUE)` - but do wait at least 60 seconds before running this code - if it doesn't work restart R `q()` and try again. 

## Network/Security

These Security Groups are standard fare for Nectar, they provide rules (many rules per group) for particular access rules. I tend to create an "RStudioServer" group with single rule for 8787, and an "SSH" group with single rule for port 22. 

The security settings are set up for your account, but are applied individually to an VM instance. You can set them at launch time, or set them after launching. 

All the defaults can be left as-is, we just set the name of the group and add a rule for the port. You may already have done this for running RStudio on Nectar.  

* Go to Network/Security Groups, click Create Security Group
* Name it **RStudioServer**, and then click its Manage Rules and add 8787
* Go to Network/Security Groups, click Create Security Group
* Name it **SSH**, and then click its Manage Rules and add 22

## Availability Zone

Availability Zone is the "node" in which the VM is launched, these are in various places around Australia. My local one is "tasmania", and that is the node where the physical disk used by the data collection actually is. This node is generally slower than other nodes, so for launching and testing it's generally faster (even for me) to allow the zone to be chosen automatically - I tend to get "intersect01". Technically, the user experience for intensive use of raadtools will be better in the tasmania node, but it's still useful that it will work anywhere.   For general use the ssh file connection seems performant enough, though for really heavy work (Gbs of data pulled into memory) I would use the tasmania node if I could.

**Comment by mdsumner** [comment]
Here's the launch instance dialog

![screenshot 2018-05-14 at 13 07 15](https://user-images.githubusercontent.com/4107631/39976647-388f6bf4-5778-11e8-8596-0653d9f1a100.png)

**Comment by mdsumner** [comment]
Here's the Access and Security tab of the launch instance dialog, note my key is called "mdsumner" - yours will have its own name. Also the security groups I've named RStudioServer and SSH, though yours might have different names they just need port 8787 and port 22 rules allowed respectively. 

![screenshot 2018-05-14 at 13 11 39](https://user-images.githubusercontent.com/4107631/39976747-ae784cb4-5778-11e8-9266-0c5181649578.png)

**Comment by adamhsparks** [comment]
In your initial instructions, I didn't scroll down and see the "Launch Instance" dialogue and selected default settings, m2.tiny, which is too small and fails to launch.

I'd explicitly include this in the instruction set.

**Comment by mdsumner** [comment]
Need to add the rutter repo in order to update beyond R 3.4.4: add-apt-repository ppa:marutter/rrutter3.5

**Comment by mdsumner** [comment]
* root access by key is compulsory
* user access by encrypted server is desired
* raadsync data library access from clients by sshfs
* define ansible recipe for [raad-clients](https://github.com/AustralianAntarcticDivision/raadtools/issues/73), client build definition is currently [Mike notes](https://github.com/mdsumner/nectar/blob/master/r-spatial.sh) + manual updates

ping @JustBerkhout

**Comment by raymondben** [comment]
For the want of a better place to put these notes, also:
- the SSHFS connection is exposed from the raadsync2 VM, the user credentials here need to be locked down to the absolute max possible
- possibly make that SSHFS host connection through a new VM so that taking raadsync2 up/down doesn't break client connections

**Comment by mdsumner** [comment]
Needs a big update in light of https://github.com/mdsumner/nectar/blob/master/openstack/create_install_rstudio_openstack.md

and then automate ftw

**Comment by JustBerkhout** [comment]
> Needs a big update in light of https://github.com/mdsumner/nectar/blob/master/openstack/create_install_rstudio_openstack.md
> 
> and then automate ftw

Could consider instructions and/or configuration scripting for use in Nectar R-Studio Application. (https://support.ehelp.edu.au/support/solutions/articles/6000164849-nectar-applications-r-studio)

**Comment by mdsumner** [comment]
thanks!
