### ISSUE TITLE
readchla not working.

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/raadtools#75]
```
library(raadtools)
date <- "2015-01-01"
readchla(date)
Error in read_oc_sochla(date, bins = bin_sub, product = product, inputfiles = files) : 
  object 'files' not found
```

**Comment by mdsumner** [comment]
Should be fixed now!

**Comment by ryanreisinger** [comment]
Doesn't seem to be on the RAATD VM

`
library(raadtools)
readchla("2015-01-05")
Error in read_oc_sochla(date, bins = bin_sub, product = product, inputfiles = files) : 
  object 'files' not found
`

**Comment by raymondben** [comment]
@ryanreisinger try now, I just reinstalled it on that VM

**Comment by ryanreisinger** [comment]
Working now. Thanks @raymondben and @mdsumner .
