### ISSUE TITLE
better error message on no files

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/raadtools#78]
Better than this

```R
 library(raadtools)
Loading required package: raster
Loading required package: sp
readtopo()
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "NULL"
readice()
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "NULL"
```

**Comment by mdsumner** [comment]
see raadfiles

**Comment by elgabbas** [comment]
I am receiving this error. Is there a solution for it?

**Comment by mdsumner** [comment]
It probably means it can't find the files. There's a fairly intensive set up requirement for raadtools, what function/s are you using and have you set things up with bowerbird?  (I wouldn't expect many folks would do this, it's not that hard but it is fairly detailed - and none of the functions in raadtools trigger the process, they just assume it's done).

**Comment by elgabbas** [comment]
Thanks Michael for your response,

Actually, I was interested in trying out how does the package determine the sea ice edge and how it calculates the distance to it. The error appears at this function (which I tried on two different windows computers):
```
library(raadtools)
#  global option 'raadfiles.data.roots' set:
# '    '
# Warning message:
# In set_raad_filenames(clobber = TRUE) : no file cache found

ice <- readice(c("2018-06-01", "2019-06-01"))
# Error in UseMethod("filter_") : 
# no applicable method for 'filter_' applied to an object of class "NULL"
```

Cheers,
Ahmed
