### ISSUE TITLE
latest/dates confusion

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#81]
If dates are provided (to e.g. `readsst`) they are silently ignored if `latest = TRUE`, which it is by default. The documentation does this, so it's intentional, but I wonder if users actually realize it. Have just found user code in the wild that got bitten by this (provided dates but did not set `latest = FALSE`, so dates were ignored). Would it make more sense for either:

- `latest` to be `FALSE` by default, so that the user *must* provide either this or dates
- `latest` is ignored if dates are provided?

Update: OK, so there's something else: `readsst(latest = FALSE)` still returns me data, but I have no idea what date it corresponds to since I have not specified dates and don't want latest.

**Comment by mdsumner** [comment]
ouch, I really want `latest = TRUE` to be the default, now - this is bad. 

I think it's ok if the argument is ignored if dates is entered, will fix. Perhaps I should make latest = NULL, so it's clear if the user specified

**Comment by mdsumner** [comment]
c9ad1ca  I think it's a simple fix!  

Will start on other cases, let me know what you think :)

**Comment by raymondben** [comment]
Was this a recent change, by the way?

**Comment by mdsumner** [comment]
I *think* it's been the default for new read  functions for a while, and in the last updates I just started blithely setting it to old ones without realizing it was overriding inputs ...

**Comment by mdsumner** [comment]
Pushed all changes out, sheesh ...  that was a good one. Lots of the args still need reviewing
