### ISSUE TITLE
error with raadtools installation in R 3.5.1

### ISSUE THREAD

**Issue by emsa999** [AustralianAntarcticDivision/raadtools#84]
When I try to install raadtools using devtools::install_github("AustralianAntarcticDivision/raadtools"), I get the following error message:

Downloading GitHub repo AustralianAntarcticDivision/raadtools@master
from URL https://api.github.com/repos/AustralianAntarcticDivision/raadtools/zipball/master
Installing raadtools
Downloading GitHub repo AustralianAntarcticDivision/raadfiles@master
from URL https://api.github.com/repos/AustralianAntarcticDivision/raadfiles/zipball/master
Installing raadfiles
Installing 1 package: rlang
Installing package into ‘C:/Users/emsa/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://pbil.univ-lyon1.fr/CRAN/bin/windows/contrib/3.5/rlang_0.3.0.1.zip'
Content type 'application/zip' length 1032147 bytes (1007 KB)
downloaded 1007 KB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’

The downloaded binary packages are in
        C:\Users\emsa\AppData\Local\Temp\RtmpCsXjXn\downloaded_packages
"C:/PROGRA~1/R/R-3.5.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/emsa/AppData/Local/Temp/RtmpCsXjXn/devtools342451b03350/AustralianAntarcticDivision-raadfiles-57abaea"  \
  --library="C:/Users/emsa/Documents/R/win-library/3.5" --install-tests 

ERROR: dependency 'rlang' is not available for package 'raadfiles'
* removing 'C:/Users/emsa/Documents/R/win-library/3.5/raadfiles'
In R CMD INSTALL
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-3.5.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/emsa/AppData/Local/Temp/RtmpCsXjXn/devtools342410392b38/AustralianAntarcticDivision-raadtools-f705cb0"  \
  --library="C:/Users/emsa/Documents/R/win-library/3.5" --install-tests 

ERROR: dependency 'raadfiles' is not available for package 'raadtools'
* removing 'C:/Users/emsa/Documents/R/win-library/3.5/raadtools'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by mdsumner** [comment]
Do you have an open session with rlang already loaded? At any rate, make sure rlang is installed and then try the raadtools install again.

Also, in case you don't know already, please note raadtools needs a significant preparation to be of much use, it doesn't have much in-built data functionality.

**Comment by emsa999** [comment]
Worked this time! Thanks!
