### ISSUE TITLE
Update topo.R to new file locations

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/raadtools#9]
topo.R currently reads some files from old gridded repo; needs updating.

gebco08 - currently bathymetry/gebco_08/gebco_08.tif, should be data_local/www.bodc.ac.uk/gebco/gebco_08.tif. I think that this has been superseded by data_local/www.bodc.ac.uk/gebco/GRIDONE_2D.nc but needs checking.

george_v_terre_adelie - should be data/data.aad.gov.au/aadc/portal/

IBCSO - should be data/hs.pangaea.de/Maps/bathy/IBCSO_v1/

kerguelen - should point to data/ftt.jcu.edu.au/deepreef/kergdem/gmt/kerg_dem_gmt/

**Comment by mdsumner** [comment]
Updated all paths in dev, need to check the interp of each and test cases. I chose 

george_v_terre_adelie - 250m (not 500 or 1000)
IBCSO - polar "is" ice surface, needs to add the projection metadata (this is polar)

**Comment by raymondben** [comment]
Sorry, george_v_terre_adelie now one subdirectory lower:
data/data.aad.gov.au/aadc/portal/4494
Had to move it to avoid clashes

**Comment by mdsumner** [comment]
This already works since the file-find is grep based on partial tokens (feature? bug? discuss)
